CREATE TABLE Libros (
	ID SMALLINT	IDENTITY(1,1) PRIMARY KEY,
	TITULO	VARCHAR(30) NOT NULL,
	AUTOR	VARCHAR(30) NOT NULL,
	FECHA_EDICION	SMALLINT NOT NULL CHECK (FECHA_EDICION BETWEEN 1900 AND 1940)
)